# Generated by Django 3.0.4 on 2020-03-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10)),
                ('unidadesC', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Materias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PNF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('materias', models.ManyToManyField(to='horario.Materias')),
            ],
            options={
                'verbose_name_plural': 'PNF',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pnf', models.ManyToManyField(to='horario.PNF')),
            ],
            options={
                'verbose_name_plural': 'Profesores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Secciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('trayecto', models.PositiveIntegerField()),
                ('trimestre', models.PositiveIntegerField()),
                ('modalidad', models.CharField(choices=[('FS', 'fin de semana'), ('ES', 'entre semana')], max_length=30)),
                ('pnf', models.ManyToManyField(to='horario.PNF')),
                ('profesores', models.ManyToManyField(to='horario.Profesores')),
            ],
            options={
                'verbose_name_plural': 'Secciones',
                'ordering': ['codigo'],
            },
        ),
    ]
