# Generated by Django 3.0.4 on 2020-03-29 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0002_auto_20200318_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesores',
            name='pnf',
        ),
        migrations.AddField(
            model_name='profesores',
            name='pnf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='horario.PNF'),
        ),
    ]
