# Generated by Django 3.0.4 on 2020-03-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0003_auto_20200328_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secciones',
            name='horarios',
        ),
        migrations.AddField(
            model_name='trimestre',
            name='Trayecto',
            field=models.PositiveIntegerField(null=True, verbose_name='Trayecto'),
        ),
        migrations.AlterField(
            model_name='materias',
            name='unidadesC',
            field=models.PositiveIntegerField(verbose_name='Unidades Curriculares'),
        ),
    ]
