# Generated by Django 3.0.4 on 2020-03-30 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0004_auto_20200329_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarios',
            name='seccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='horario.Secciones'),
        ),
        migrations.AddField(
            model_name='profesores',
            name='Materia del Profesor',
            field=models.ManyToManyField(blank=True, to='horario.Materias'),
        ),
    ]
