# Generated by Django 3.0.4 on 2020-03-30 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0005_auto_20200330_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesores',
            old_name='Materia del Profesor',
            new_name='materias',
        ),
    ]
