# Generated by Django 3.0.4 on 2020-04-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0007_salones'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarios',
            name='posicion',
            field=models.TextField(default=None, max_length=500),
        ),
    ]
