# Generated by Django 3.0.4 on 2020-04-18 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0008_horarios_posicion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horarios',
            options={'ordering': ['codigo'], 'verbose_name_plural': 'Secciones'},
        ),
    ]
