# Generated by Django 3.0.4 on 2020-04-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0009_auto_20200418_0421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horarios',
            options={'ordering': ['codigo'], 'verbose_name_plural': 'Horarios'},
        ),
    ]
