# Generated by Django 3.0.4 on 2020-04-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0010_auto_20200419_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='posicion',
            field=models.TextField(default=None, max_length=5000),
        ),
    ]
